import '../models/app_models.dart';

class DummyData {
  static List<UserProfile> get profiles => [
    UserProfile(
      id: '1',
      name: 'Aisha',
      age: 24,
      bio: "Coffee lover and adventure seeker. Looking for someone to explore life with.",
      occupation: 'Software Engineer',
      education: 'UDSM Graduate',
      region: 'Dar es Salaam',
      distance: 3.2,
      interests: ['Music', 'Travel', 'Technology', 'Cooking'],
      relationshipGoal: 'Serious Relationship',
      verified: true,
      online: true,
    ),
    UserProfile(
      id: '2',
      name: 'Zainab',
      age: 26,
      bio: "Entrepreneur with a passion for fashion. Let's build something great together.",
      occupation: 'Business Owner',
      education: 'Mzumbe University',
      region: 'Dar es Salaam',
      distance: 5.8,
      interests: ['Fashion', 'Business', 'Movies', 'Photography'],
      relationshipGoal: 'Marriage',
      verified: true,
      online: false,
    ),
    UserProfile(
      id: '3',
      name: 'Rehema',
      age: 23,
      bio: "Medical student who loves reading and quiet evenings. Seeking a kind soul.",
      occupation: 'Medical Student',
      education: 'MUHAS',
      region: 'Dar es Salaam',
      distance: 2.1,
      interests: ['Reading', 'Sports', 'Music'],
      relationshipGoal: 'Dating',
      verified: false,
      online: true,
    ),
    UserProfile(
      id: '4',
      name: 'Neema',
      age: 25,
      bio: "Teacher by day, dancer by night. Life is too short for boring company.",
      occupation: 'Teacher',
      education: 'University of Dodoma',
      region: 'Dodoma',
      distance: 12.4,
      interests: ['Music', 'Sports', 'Travel', 'Cooking'],
      relationshipGoal: 'Friendship',
      verified: true,
      online: false,
    ),
    UserProfile(
      id: '5',
      name: 'Fatuma',
      age: 27,
      bio: "Marketing professional who loves the beach and good conversations.",
      occupation: 'Marketing Manager',
      education: 'TUM',
      region: 'Dar es Salaam',
      distance: 7.3,
      interests: ['Business', 'Travel', 'Photography', 'Fashion'],
      relationshipGoal: 'Serious Relationship',
      verified: true,
      online: true,
    ),
  ];

  static List<Match> get matches => [
    Match(
      user: profiles[0],
      matchedAt: DateTime.now().subtract(const Duration(hours: 2)),
      lastMessage: "Hey! Nice to match with you 😊",
      lastMessageTime: DateTime.now().subtract(const Duration(minutes: 30)),
      unreadCount: 2,
    ),
    Match(
      user: profiles[1],
      matchedAt: DateTime.now().subtract(const Duration(days: 1)),
      lastMessage: "Let's meet up this weekend?",
      lastMessageTime: DateTime.now().subtract(const Duration(hours: 5)),
      unreadCount: 0,
    ),
    Match(
      user: profiles[4],
      matchedAt: DateTime.now().subtract(const Duration(days: 3)),
      lastMessage: "I loved your profile!",
      lastMessageTime: DateTime.now().subtract(const Duration(days: 1)),
      unreadCount: 1,
    ),
  ];

  static List<AppNotification> get notifications => [
    AppNotification(
      id: '1',
      type: 'match',
      title: 'New Match!',
      body: 'You and Aisha liked each other.',
      time: DateTime.now().subtract(const Duration(minutes: 30)),
    ),
    AppNotification(
      id: '2',
      type: 'message',
      title: 'New Message',
      body: 'Zainab sent you a message.',
      time: DateTime.now().subtract(const Duration(hours: 5)),
    ),
    AppNotification(
      id: '3',
      type: 'like',
      title: 'Someone Liked You',
      body: 'Rehema liked your profile.',
      time: DateTime.now().subtract(const Duration(hours: 8)),
    ),
    AppNotification(
      id: '4',
      type: 'super_like',
      title: 'Super Like!',
      body: 'Neema super liked you.',
      time: DateTime.now().subtract(const Duration(days: 1)),
      read: true,
    ),
    AppNotification(
      id: '5',
      type: 'verification',
      title: 'Verification Approved',
      body: 'Your profile verification was approved.',
      time: DateTime.now().subtract(const Duration(days: 2)),
      read: true,
    ),
  ];
}
